return {
	-- "nvim-tree/nvim-tree.lua",
	-- dependencies = "nvim-tree/nvim-web-devicons",
	-- version = "*",
	-- lazy = false,
	-- config = function()
	-- 	vim.g.loaded_netrw = 1
	-- 	vim.g.loaded_netrwPlugin = 1
	-- 	vim.g.nvim_tree_git_hl = 1
	--
	-- 	local icons = require("config.icons")
	--
	-- 	require("nvim-tree").setup({
	-- 		filters = {
	-- 			dotfiles = false,
	-- 			exclude = { vim.fn.stdpath("config") .. "/lua/custom" },
	-- 		},
	-- 		disable_netrw = true,
	-- 		hijack_cursor = true,
	-- 		update_focused_file = {
	-- 			enable = true,
	-- 			update_root = false,
	-- 		},
	-- 		view = {
	-- 			adaptive_size = false,
	-- 			side = "left",
	-- 			width = 35,
	-- 		},
	-- 		git = {
	-- 			ignore = false,
	-- 		},
	-- 		modified = {
	-- 			enable = true,
	-- 		},
	-- 		filesystem_watchers = {
	-- 			enable = true,
	-- 		},
	-- 		actions = {
	-- 			open_file = {
	-- 				resize_window = true,
	-- 			},
	-- 		},
	-- 		renderer = {
	-- 			highlight_git = true,
	-- 			-- highlight_opened_files = "none",
	-- 			root_folder_label = false,
	--
	-- 			indent_markers = {
	-- 				enable = false,
	-- 			},
	--
	-- 			icons = {
	-- 				show = {
	-- 					file = true,
	-- 					folder = true,
	-- 					folder_arrow = true,
	-- 					git = true,
	-- 				},
	--
	-- 				glyphs = {
	-- 					default = "",
	-- 					symlink = "",
	-- 					folder = {
	-- 						default = "",
	-- 						empty = "",
	-- 						empty_open = "",
	-- 						open = "",
	-- 						symlink = "",
	-- 						symlink_open = "",
	-- 						arrow_open = "",
	-- 						arrow_closed = "",
	-- 					},
	-- 					git = {
	-- 						unstaged = "",
	-- 						staged = "",
	-- 						unmerged = "",
	-- 						renamed = "➜",
	-- 						untracked = "⏺",
	-- 						deleted = "⏺",
	-- 						ignored = "◌",
	-- 					},
	-- 				},
	-- 			},
	-- 		},
	-- 		diagnostics = {
	-- 			enable = true,
	-- 			show_on_dirs = true,
	-- 			show_on_open_dirs = true,
	-- 			debounce_delay = 50,
	-- 			severity = {
	-- 				min = vim.diagnostic.severity.HINT,
	-- 				max = vim.diagnostic.severity.ERROR,
	-- 			},
	-- 			icons = {
	-- 				hint = icons.diagnostics.Hint,
	-- 				info = icons.diagnostics.Info,
	-- 				warning = icons.diagnostics.Warning,
	-- 				error = icons.diagnostics.Error,
	-- 			},
	-- 		},
	-- 	})
	-- end,
}
